### ISSUE TITLE
sample meta-data

### ISSUE THREAD

**Issue by abyot** [abyot/sun-pmt#1]
We need sample meta-data to test with basic stuff.

**Comment by kreinhardt** [comment]
I've added the meta-data working doc to google drive and shared it with you.

**Comment by abyot** [comment]
Great, thanks.

**Comment by kreinhardt** [comment]
Should I start entering the metadata into the system? I can start with the simple stuff like the Actions and the delivery mechanisms.

**Comment by abyot** [comment]
Yes, please do that.

**Comment by abyot** [comment]
Hi @kreinhardt  

I have added a new folder - **Situation_Indicator_CSV_Data** -  in drive. The folder contains two files - imported and not_yet_imported. I have tested the formatting.

To import go to Apps -> Import-Export -> Data Import  and use CSV as Format

**Comment by abyot** [comment]
Imported.
