### ISSUE TITLE
Actions point for reporting section from 03/08 call

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#10]
**(1) Descriptions of reports on the home page of the Report section**: 
- [x] Kris will send text for descriptions under the three reporting options on the home page of reports

**(2) Organization unit options for all reports**: The user will be given the option to view the report at the selected organization unit or at one level below (e.g. if national level is selected, the user will have the option to run the report for the national level or for all organization units that one level below the national level).
- [x] Abyot will make this change

**(3) Context for all reports**: We would like to add a description for each report that is generated in order to support the interpretation of the data presented. This will be especially important for the geographic coverage data, which is often hard to interpret. In addition, viewers should know that there could be multiple stakeholders doing the same action and that they should not add/sum across stakeholders.
- [x] Kris will send mock-up/text for each report

**(4) Order of columns on Who Does What report**: Request to reorganize the columns so that all the stakeholder roles are together and the delivery mechanisms column is at either end of the table. The stakeholder roles can be in any order as long as they are grouped. 
- [x] Abyot will make this change

**(5) Field Implementer option for both Population and Geographic Coverage per Stakeholder reports**: We would like to add field implementers to the possible reports.  
- [x] Abyot will try to do this – it may be difficulty considering that the field implementer data is different from the other stakeholder data

**(6) Population Coverage per Stakeholder reports**: We should be able to run the population coverage per stakeholder report at the district level because we have district level data. Currently, there is a message saying that a higher organization unit needs to be selected.
- [x] Abyot will make this change

**(7) Downloadable report**s: We would like to be able to download the reports as PDFs or Excel files. 
- [x] Abyot will make this change

**Comment by kreinhardt** [comment]
Here is the descriptive text and icon changes for the 3 reports:

**Who does what:**
"Table of all stakeholders involved in each action, listed by role (_field implementer, catalyst, funder_ and _responsible ministry_) and by delivery mechanisms."
[Icon "street-view"](http://fontawesome.io/icon/street-view/)

**Population coverage:**
"Table of the percentage of total beneficiaries that is covered by each stakeholder, listed by role (_field implementer, catalyst, funder_ and _responsible ministry_)."
[Icon "bar-chart"](http://fontawesome.io/icon/bar-chart/)

**Geographic coverage:**
"Table of the number and percentage of geographic areas reached by each stakeholder, listed by role (_field implementer, catalyst, funder_ and _responsible ministry_)."
[Icon "map"](http://fontawesome.io/icon/map/)

Mock up/text also here: https://drive.google.com/open?id=0B9AJjRbFGuGtVmhTd0lyeTRFMWM

**Comment by kreinhardt** [comment]
The templates/mock ups for the reporting sheets can be found [here](https://drive.google.com/a/caa.columbia.edu/file/d/0B9AJjRbFGuGtTnNRUks0cnhMN1k/view?usp=sharing).

**A couple questions/requests:**
1. On all three of the reporting sheets, can you make the boxes for the list of actions wider so that you can read the whole action name? Or at least most of the title?
2. For the geographic and population coverage reports, can there be text that appears directly above the table depending on the stakeholder role selected? I want to provide a note for users when the Catalyst, Funder and Responsible Ministry roles are selected. See mock up for example.
3. I don't think that coverage is being calculated correctly when the reporting level is selected as district or province. Please see slide 4 in the mockup for a table of calculations that should be taking place.

**Comment by abyot** [comment]
Regarding the calculation, I was thinking the same. Actually initially we were doing as you mentioned but changed it.

Just a question: are you sure the calculation at district level is wrong? What I think will be affected is those calculations at national and province level. I don't think district level - since we are collecting data at district level - is going to be affected.

What we are doing currently is:

For national level: pick only those districts that have data. For these districts, pick their denominator data. This will give us, the same number of numerators and denominators. We will then divide the sum of numerators with sum of denominators. 

We are doing the same for province level. For each province pick those districts with data.

What you are suggesting now is... pick all districts whether they have data or not. Is this correct?

For example what will happen if a district does not have denominator data? Should this district be included or not?

**Comment by kreinhardt** [comment]
So there seems to be two issues:

**1**- The denominators should always be the total districts or target group population at whichever organization unit and reporting level that have been selected. 
- **Geographic coverage**: the denominator should be the total number of districts in country (national level), total number of districts in a particular province (province level) or 1 (district level)

- **Population coverage**: the denominator should be the total population of a particular target group at the national, province or district levels. 

We would not expect that there will be missing district data as we would use some kind of estimate for these number depending on the data available at country level. 


**2**- The second issue is when the "reporting level" is set to province/district level the calculation is not showing the correct level of data (it no longer is the same as the selected organization unit but rather with the level below)
