### ISSUE TITLE
Text and visualization of mapping module / data entry

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#16]
- [x] **Organization unit info bubble**: Please change the text of the info bubble to: 

The organization unit refers to the geographic area of focus for data entry. Using the menu on the left, select the geographic entry point. The entry point refers to the geographic level directly above the level for which data will be entered.

- [x] **Warning on right side**: Please change the text of the warning box to: 

**Warning**: On 29 Aug 2016, user **admin** last entered data for the same action, year, delivery mechanism, field implementer and geographic location.

If the Additional Stakeholders or the number of beneficiaries that were previously entered are not correct, please complete or revise the information. If you have further questions, please contact the system administrator.

- [x] **Additional Stakeholders info bubble**: Please change the text in this bubble to: 

The stakeholder for a particular action may include government ministries/institutions, international and national non-government organizations, UN agencies, donors, academic/research institutions, private sector, etc.

- [x] **Responsible ministry info bubble**: Please change the text in this bubble to: 

The Responsible Ministry sets the policy, legislative infrastructure and/or overall strategic direction of the action from the side of the government.

- [x] **Additional stakeholders section**: Can you move the text after the info bubble to the line below and change it to read:

For this action, specify which stakeholders are involved in each role. If there is no stakeholder in a particular role, leave the space blank. If there are multiple stakeholders in a particular role, more than one stakeholder may be entered.

- [x] **Text under Catalyst/Funder/Responsible Ministry boxes**: Please change the text to:

If the stakeholders differ across the geographic areas and target groups displayed below, use the {icon} icon to modify the stakeholders supporting each geographic area and target group.

- [x] **Additional Stakeholder pop-up**: Please change the text to: 

## Additional Stakeholder for [district name]
If the Additional Stakeholders differ in this geographic area or across the target groups in this geographic area, please make the necessary modifications here.

- [x] **Additional Stakeholder pop-up**: please remove the text circled in the picture below:
![image](https://cloud.githubusercontent.com/assets/10057077/18096264/e33c1946-6ed9-11e6-979d-ce05ff06b044.png)

- [x] **Text for completeness buttons**: Can you change the text to “Mark complete” “Mark incomplete”?

**Comment by abyot** [comment]
These are all fixed.

**Comment by kreinhardt** [comment]
Can you change the text here to black?

![image](https://cloud.githubusercontent.com/assets/10057077/18173526/31e3d58e-706a-11e6-98f2-e84c1962acb2.png)

**Comment by kreinhardt** [comment]
Can you change the Additional Stakeholders pop-up box title to:
**Additional Stakeholders for [district name]**
instead of "Additional Stakeholder for [district name]"
(Sorry, this was my mistake in my previous request)

**Comment by abyot** [comment]
@kreinhardt  this is fixed.
