### ISSUE TITLE
defining data elements

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#2]
When defining a data element, I have been completing the following aspects of the form:
- Name: <action+target group> or  <delivery mechanisms>
- Short name: short version of <action+target group> or <delivery mechanisms>
- Domain type: Aggregate
- Value type: number
- Aggregation operator: sum
- Aggregation level: national, province, district (data will be collected at the district level from each stakeholder)

Is this correct? Should I be using other options and/or completing more of the form?

**Comment by abyot** [comment]
Yes, that is correct. But on the value type, what are we expecting - are we expecting all type of numbers? or only positive numbers that make sense since we will be counting?

For the category combination - leave it as "default" for now. We will change it later.

Also, as we go further, expect some back-and-forth on the meta-data definition. i.e. we might redo some of the stuff.

**Comment by kreinhardt** [comment]
For the value type, we would only expect positive, whole numbers (people!). I will change the value type to <positive integer>. 

Since we want to bring together action+target group, delivery mechanism, stakeholders(by role) - do  all these data elements have the same data type? In the end, for each combination of action, delivery mechanism, and stakeholders we will only have a single value (beneficiaries).

**Comment by abyot** [comment]
Yes, we will have only one value type. The data element is just one - for example "number of beneficiaries of .....". This data element, in your vocabulary "action", will have two sets of dimensions. The first set of dimension tells us more like the what of the data or the "target group". By target group, I suspect you are referring to gender and age dis-aggregation (we can have more).

The second set of dimension is about the "how" of the data - how the action was delivered - for example by stakeholder/agency A through delivery mechanism B using channel C....

These two sets of dimensions are defined as category and category combination. There is this property called "Data dimension type" with value either "Attribute" for the **_how_** of data or "Disaggregation" for the **_what_** of data.

We can discuss more on Monday and come up with better meta-data design.

**Comment by abyot** [comment]
Discussed.
