### ISSUE TITLE
Text and visuals for the mapping module // reporting

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#20]
- [x] For all three reporting tabs can you add a line at the top of the Report Filter that says: 

**Select the geographic area from the list on the left***

- [x] For Who Does What and Geographic Coverage reporting tabs can you add a line of text above the action selection section that says:

**Actions (select one or more)*** 

For the Population Coverage reporting tab can the text be:

**Actions and target groups (select one or more)*** 

- [x] Are you able to add text above the Geographic and Population coverage tables when the role selected is Catalyst, Funder or Responsible Ministry? 

For the Population Coverage: 

Note: If catalyst, funder or responsible ministry have been selected as the stakeholder role, the coverage of beneficiaries cannot be summed across the actions. 

For the Geographic Coverage:

Note: If catalyst, funder or responsible ministry have been selected as the stakeholder role, the number and percentage of geographic areas cannot be summed across the actions. 

See mock up for further details https://drive.google.com/a/caa.columbia.edu/file/d/0B9AJjRbFGuGtUmZ2M0Y1MnZRUEk/view?usp=sharing

**Comment by kreinhardt** [comment]
Can you adjust the punctuation for the **Who does what** subtitle on the first reports page to:
Table of all stakeholders involved in each action listed by role (field implementer, catalyst, funder and responsible ministry) and by delivery mechanisms.

![image](https://cloud.githubusercontent.com/assets/10057077/18197919/258b77d4-70fa-11e6-86f7-12c35cd28ea7.png)

**Comment by abyot** [comment]
@kreinhardt  

These are all fixed except for calculations of population and geographic coverage reports. Is it possible to get more information for these reports? 

For example for the geographic coverage, if we are not adding up areas across action what are we going to display as a result? The report is about geographic coverage. Similarly, for the population coverage, what should we add?

**Comment by kreinhardt** [comment]
**Geographic coverage:**
For Stakeholder A in a particular role, we are asking if the action has taken place in each district across each report of that action (same action+target group+year but with different field implementer) that they are involved in. This value is then filtered by and aggregated to the province/national level. See table below for example:
![image](https://cloud.githubusercontent.com/assets/10057077/18242450/a74d01bc-7356-11e6-963f-b8f4092eb214.png)


**Population coverage:**
Similar logic as the above can be applied to the population coverage, except we do not want to convert values to binary and we use the total population values to calculate a coverage. See table to calculations:
![image](https://cloud.githubusercontent.com/assets/10057077/18242602/5f01f5ce-7357-11e6-9ae8-f44904c53b35.png)

**Comment by abyot** [comment]
@kreinhardt 

Thanks for the details. A question though, sorry that I am still asking for more details :(

Can you give more concrete example like you have in #19 so that I can go and check with real data we have in the system?

**Comment by kreinhardt** [comment]
[Rwanda pop. and geo. calculations for school children recieving school feeding.xlsx](https://github.com/abyot/sun-pmt/files/454816/Rwanda.pop.and.geo.calculations.for.school.children.recieving.school.feeding.xlsx)


Here the excel document I was using to check the calculations in DHIS2 - you can see the formulas used. Let me know if you need further details!

**Comment by abyot** [comment]
Ok great. I was asking if you have put some of these data in the system.

If not, I will put some myself and do the crosschecking. 

Can I clear existing action related data from the system?

**Comment by kreinhardt** [comment]
I input data for 2014 in the system that matches the data that is in the excel - you'll see that the data for the population coverage for Nyarugur and Nyamagabe do not match. 

You may need to enter additional data to test geographic coverage though since in the current data set, the number match up however the system could just be measuring the coverage for a single instance.

**Comment by abyot** [comment]
Ok good. In the case, we have

Period:  2104
Province: South
Delivery mechanism: ??
Field Implementer: ??

**Comment by abyot** [comment]
@kreinhardt Below is what I am getting (I haven't entered any data). Is this not correct?

![image](https://cloud.githubusercontent.com/assets/4967749/18245379/27dc41d6-7365-11e6-85a6-86716d904a25.png)

**Comment by kreinhardt** [comment]
@abyot the above is correct. I didn't find any issues with the geographic coverage, only the population coverage and for the responsible ministry role. Everything else was showing the correct results.

**Comment by abyot** [comment]
@kreinhardt 

See what I have found out.

![image](https://cloud.githubusercontent.com/assets/4967749/18256050/5b04e248-73b0-11e6-85fa-2ca35145bdfc.png)

![image](https://cloud.githubusercontent.com/assets/4967749/18256078/caf66504-73b0-11e6-915a-25be65d30a83.png)

![image](https://cloud.githubusercontent.com/assets/4967749/18256086/e78a5cc0-73b0-11e6-9a5a-ac8c56482bb4.png)

**Comment by kreinhardt** [comment]
Hi @abyot - I'm not clear what the first image is showing. But I just ran the population coverage and it looks fine:
![image](https://cloud.githubusercontent.com/assets/10057077/18265412/df39a21e-7415-11e6-89f0-1c0da03c3b17.png)

**Comment by abyot** [comment]
Hi @kreinhardt ,

The first image was when tracing disaggregated values for both numerator and denominator. The figure shows there were two entries (12743 and 12474) for Ministry of Education. Because you were telling me the calculation was wrong. But it turns out it is correct, the issue was there was another entry.
