### ISSUE TITLE
How do I add more actions to the Mapping module?

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#21]
I would like to enter more stakeholder data to the system. 

It seems like the following actions have been added as Categories and have the proper target groups assigned to them:
-Promote optimal breastfeeding practices
-Promote optimal complementary feeding practices
-Provide specialized nutritious products for complementary feeding
-Provide and support treatment of MAM
-Provide deworming tablets
-Provide/support improved sanitation
-Provide/support improved water source
-Promote hygiene / hand washing
-Provide school feeding

**Comment by abyot** [comment]
Yes, we have most of the pieces in place. We just need to assemble them.

One question: How do we model those actions that target a single group? In DHIS 2 we have what we call a "Default" dimension - i.e. this is the same whether you target a single group or nothing. See a sample screenshot below:

![image](https://cloud.githubusercontent.com/assets/4967749/18230546/1a42662a-729f-11e6-88cb-af8cf351c4be.png)

As you can see the target group heading says "Value" - i.e. there is no as such an explicit target group. The fact that the data element is collected means and implicit group has been targeted. This saves us from creating unnecessary target group.

**Comment by kreinhardt** [comment]
I don't think that it should say "value" - it should say the name of the target group. 

In the mapping methodology, we direct countries to assign target groups to each action, so it doesn't seem like assigning one or more should be more work than we already expect countries to do.

Isn't the target group already created since we have to create that element in order to enter the total target group population data?

**Comment by abyot** [comment]
@kreinhardt 

We haven't created a target group for those actions focused on a single target group. We have a default target group that applies automatically when an action (or data element) is focused on single target.

We can create an explicit target group with respective naming convention instead of using "Default".

**Comment by kreinhardt** [comment]
That would be best - we need to make sure the user entering data know what data (target group) to report.

**Comment by abyot** [comment]
@kreinhardt  Sure, we can do that. But my point was the user should know more the data its target group (or dimension).

**Comment by abyot** [comment]
@kreinhardt We have not 23 actions and corresponding target groups defined in the system. What remains is definition of indicators for population coverage.
