### ISSUE TITLE
Data appearing under incorrect field implementer

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#22]
I entered the following data for field implementer (different delivery mechanisms):
**(1)**
![image](https://cloud.githubusercontent.com/assets/10057077/18348058/770925f6-75c9-11e6-83b3-af40a1bb4faf.png)
**(2)**
![image](https://cloud.githubusercontent.com/assets/10057077/18348078/8e0e9024-75c9-11e6-9888-21d540cdc7b4.png)

When attempting to enter data for another field implementer, I found that there was already data present that matched the previously entered data. 
![image](https://cloud.githubusercontent.com/assets/10057077/18347186/7ae2a8dc-75c4-11e6-80a3-5b5567e9df4c.png)
![image](https://cloud.githubusercontent.com/assets/10057077/18347187/7ed75d34-75c4-11e6-87e2-62ad9df02edc.png)

I didn't enter this data and the numbers and districts match the data I had entered for the first field implementer. Can you check why/how this is happening?

**Comment by kreinhardt** [comment]
UPDATE: I entered all the data for another action and did not come across this issue again. Maybe is was a fluke or something I did (not sure what it could have been since I've been entering data the same way across both actions)?

**Comment by abyot** [comment]
ok, great. I was doing a little investigation and the form is cleared every time changes are made in the green area.

**Comment by kreinhardt** [comment]
Ok - I'll keep entering data and hopefully won't come across it again.

**Comment by kreinhardt** [comment]
So I went to edit this data, doing the following:
![image](https://cloud.githubusercontent.com/assets/10057077/18352122/63fbdb98-75dd-11e6-8eb1-73e95b1995e9.png)

I "completed" this action. Closed my browser and logged back. I found this: 

![image](https://cloud.githubusercontent.com/assets/10057077/18352154/85d2aa1c-75dd-11e6-829a-1d6bc5494e3e.png)

(not in the screen shot but the action un-comlpeted itself)

**Comment by kreinhardt** [comment]
Also - I'm finding the same numbers across delivery mechanisms...
![image](https://cloud.githubusercontent.com/assets/10057077/18352346/57a18842-75de-11e6-9966-d318badf4a13.png)
![image](https://cloud.githubusercontent.com/assets/10057077/18352390/8fc8d48c-75de-11e6-870b-58f146ca2968.png)

I definitely didn't enter these...

**Comment by kreinhardt** [comment]
@abyot I have not come across this issue again - it seems to be fixed. Can we close this issue?

**Comment by abyot** [comment]
Yes.
