### ISSUE TITLE
Stakeholder names to remove

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#23]
- Stakeholder 1
- Stakeholder - 2
- REACH-1
- REACH-2
- Catalyst - 1
- Funder-1
- Funder-2
- Catalyst-2
- Stakeholder-3
- HISP UiO

Also, on the original list "The Access Projech" should be "The Access Project". I checked the data element and it has a T... maybe it is just how it looks on my computer.

**Comment by abyot** [comment]
stakeholders removed.
