### ISSUE TITLE
District-specific stakeholders

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#26]
(Hi Abyot - I'm back!!)

I'm finding an issue when entering stakeholders specific to the district level. I am encountering an issue when I do the following:

For the unique identifier:
Org unit: North
Action: Carry out nutrition education
Year: 2014
Delivery Mechanism: Community
Field Implementer: Society for Family Health

I first entered the additional stakeholders as follows:
Catalyst: Catholic Relief Services, Rwanda Nutrition Society
Funder: Scaling up Nutrition Multi-Partner Trust Fund
Responsible Ministry: Ministry of Health

Then for 2 districts (Gakenke and Musanze) I wanted to change the additional stakeholders to the following:
Catalyst: (blank)
Funder: USAID
Responsible Ministry: Ministry of Health

Which I did but when I left and returned to the action I found the additional stakeholders to be the following: 
Catalyst: Catholic Relief Services, Rwanda Nutrition Society
Funder: USAID
Responsible Ministry: Ministry of Health

I think that one of the reasons this may be happening is that when you open the additional stakeholders for a district the stakeholder you have entered are not present. You have to leave the action and come back for them to appear.

Ideally, it would be good if the additional stakeholders would show up right away in the district-specific pop-up so they can be modified properly the first time through.

**Comment by abyot** [comment]
Hey, welcome back !

Will look into this.

**Comment by kreinhardt** [comment]
Hi @abyot have you been able to look into this? I think it will be good for the overall province stakeholders selected to appear right away when the user tries to edit the district-specific stakeholders.

**Comment by kreinhardt** [comment]
hi @abyot, have you been able to look into this?

**Comment by abyot** [comment]
Yes, and fixed.

**Comment by kreinhardt** [comment]
This looks great! Thank you!
