### ISSUE TITLE
Add new stakeholder not on list

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#27]
After I add the last stakeholder (Women Investment Fund) and went to add an additional stakeholder, I found that the list of stakeholders no longer has the option to add a new:
![image](https://cloud.githubusercontent.com/assets/10057077/18634337/c9631b76-7e80-11e6-9b6f-9d75e569a0ff.png)

![image](https://cloud.githubusercontent.com/assets/10057077/18634352/d7d99fe0-7e80-11e6-8e71-06a1f78264c7.png)

**Comment by abyot** [comment]
This is interesting. I will take a look to it today.

**Comment by abyot** [comment]
Just looked into this. The thing is related to paging. To speedup UI loading, the dropdown displays only a maximum f 50 options. But you can always search for those options which are not displayed in the first page... see below:

![image](https://cloud.githubusercontent.com/assets/4967749/18646786/6ffec110-7eb3-11e6-8f2b-edc8f7ad5bfd.png)

Increasing the page size will not be a lasting solution neither will it be efficient interms of loading. What I suggest is either to inform users to do search for "Add New Stakeholder" or display "Add New Stakeholder" always at the top.

I like the idea of searching. That way user will get into the habit of searching any stakehodler which is not displayed in the first list.

What do you think?

**Comment by kreinhardt** [comment]
Ok, thanks! This makes sense. I agree that the user should search for what they need rather than having the new stakeholder at the top. 

Do you think is is possible the change the text that appears in the stakeholder boxes to just say [search from list or type "new" to add]? I'm not sure if that is too long or not.

**Comment by abyot** [comment]
Sure, possible. Will fix that.

**Comment by abyot** [comment]
This is fixed.
