### ISSUE TITLE
Searching for stakeholders by full name and abbreviation

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#29]
It seems like you usually have to search for the stakeholders full name in order to find it (i.e. typing UNICEF does not produce the United Nations Children's Fund). However, it seems like it is searching both in the following case:

![image](https://cloud.githubusercontent.com/assets/10057077/18663356/879bbbf0-7f1e-11e6-9914-5653b99c70cd.png)

**is it possible to be able to search for a stakeholder using either the full name or the abbreviation?**

**Comment by kreinhardt** [comment]
ok - it seems like it is only doing it for stakeholders that have been added and not those in the original metadata. 

Were abbreviations not added to the original metadata?

**Comment by kreinhardt** [comment]
Sorry, amendment to my last comment - only some stakeholders can be found by their abbreviation not all... regardless of if they were part of the original metadata or not.

**Comment by abyot** [comment]
I get what you mean. I fill make a fix so that it becomes possible to search both on abbreviation and full name.

**Comment by abyot** [comment]
This is fixed.
