### ISSUE TITLE
"object already exists"

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#3]
I'm having an issue adding the actions, for some actions, I keep on getting the notification that the object already exists even though I have not yet added it nor is it in my list of data elements.

**Comment by abyot** [comment]
Ok great. 

When you have some issues like this, take a screenshot or whatever is displayed under browser log (if you are in chrome Tools -> Developer tools -> console).

**Comment by kreinhardt** [comment]
![object already exists](https://cloud.githubusercontent.com/assets/10057077/14911871/8af507b2-0df8-11e6-85c3-6b5b3d520a14.PNG)

**Comment by kreinhardt** [comment]
I removed Zotero that was presenting the error but is still happening. 
![object already exists 2](https://cloud.githubusercontent.com/assets/10057077/14912054/07e3acb4-0dfa-11e6-9e91-21703b704635.PNG)

**Comment by abyot** [comment]
Oh I see. In general, this is harmless. You should be able to continue working. But this will to be fixed.
