### ISSUE TITLE
Text for overriding stakeholders

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#30]
![image](https://cloud.githubusercontent.com/assets/10057077/18665180/3ecf448e-7f26-11e6-9acd-86ff78a31457.png)

Can you change the text that appears above the override checkbox to: 

**Warning:** selecting "override roles" will delete the stakeholders that have been individually assigned to the geographic areas and target group(s) below, and replace them all with the stakeholders that were selected in the section above.

**Comment by abyot** [comment]
Fixed.
