### ISSUE TITLE
How do you add new stakeholders under the responsible ministry role?

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#31]
I have added two more stakeholders, both ministries - how do I get them to appear under the responsible ministry role?

The ministries are Ministry of Infrastructure and Ministry of Disaster Management and Refugee Affairs

(I accidentally left these off before - we still would assume that the country would provide a full list of ministries with the initial metadata)

**Comment by abyot** [comment]
This is done by going through the "Maintenance Module". Specifically using the following two steps:

1. by adding them as category option, and then making them part of the "Field Implementer" category
2. OTHER -> Option set -> Responsible Ministry -> Edit -> Options
