### ISSUE TITLE
Data not be recorded

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#33]
When entering data, I entered data but found that the beneficiary numbers entered have disappeared when I go back to the same unique identifier:
![image](https://cloud.githubusercontent.com/assets/10057077/18743452/5d544546-80b9-11e6-8de4-e2449f844f00.png)

The stakeholders that I have customized at the district level are still in place but not the numbers. 

Here is the developer log: 
![image](https://cloud.githubusercontent.com/assets/10057077/18743476/80a21e2e-80b9-11e6-8762-b4f6527d9e3f.png)
(we have been having issues with the wifi here but I have since switched to LAN.

**Comment by abyot** [comment]
Are you sure the input box has turned to green when saving data?

Can you reproduce?

**Comment by kreinhardt** [comment]
Yes the box turned green: 
![image](https://cloud.githubusercontent.com/assets/10057077/18743575/f5608b74-80b9-11e6-8a27-ff0ee6b356f4.png)

After:
![image](https://cloud.githubusercontent.com/assets/10057077/18743605/0fb7f0e8-80ba-11e6-8cf7-c1fcb509721b.png)

**Comment by abyot** [comment]
Ok, good. I will investigate further.

**Comment by abyot** [comment]
@kreinhardt 

Just made some db cleanup.... see if everything is in place.

**Comment by kreinhardt** [comment]
It didn't work the first time I tried but it seems to be working now (I cleared my cache and re-logged in)

**Comment by abyot** [comment]
yes you need to clear your browser cache... sorry should have mentioned that.

one more thing, can you check if my db cleanup did not mess other things?

can you randomly check if previously entered data are not affected and also completeness?

I do not expect an issue with previously entered data, but there could be with completeness :(

**Comment by kreinhardt** [comment]
I did some checks across actions and I didn't find any issues - the data seems to be there and completeness still marked.
