### ISSUE TITLE
Issue with 'additional stakeholders'

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#34]
When checking some data today - I found this in one of the entries:
![image](https://cloud.githubusercontent.com/assets/10057077/19151862/701c6dc2-8bcf-11e6-92ad-3149bb116692.png)
The correct funder should read: Catholic University of Leuven

**Comment by kreinhardt** [comment]
Found another instance of it: 
![image](https://cloud.githubusercontent.com/assets/10057077/19151964/ec9c7e28-8bcf-11e6-8b63-3f38e33a9bb4.png)

for the identifier: 
![image](https://cloud.githubusercontent.com/assets/10057077/19151979/fece5ed6-8bcf-11e6-8542-7d332943d83a.png)

**Comment by kreinhardt** [comment]
hi @abyot, have you been able to look into this?

**Comment by abyot** [comment]
Yes, and fixed.

**Comment by kreinhardt** [comment]
Thanks @abyot  - this seems to not be happening now. 

However, I've come across related issue - when entering an additional stakeholder and then removing this is coming up:
![image](https://cloud.githubusercontent.com/assets/10057077/19435617/e8a70898-946b-11e6-9c87-6844ca01eab2.png)

I'm pretty sure this wasn't happening before.

**Comment by abyot** [comment]
Ut happened before because the selected stakeholder was outside the paging limit (it was selected after doing a a search). Now I have made the pagend size 1000, earlier it was 50.


It could happen again if we have stakeholder list goes more than 1000. I am kind if gambling this will never be rached...

**Comment by kreinhardt** [comment]
ok - it's fine. It's not really a big issue. 

I don't think that we would reach more than a 1000 stakeholders. So far it seems like the max number of stakeholder has been around 200 in countries where we have done the mapping.
