### ISSUE TITLE
Visualizations not showing up when added to dashboard

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#35]
I have been having trouble adding graphs of data elements to the dashboard: 
![image](https://cloud.githubusercontent.com/assets/10057077/19185986/58489efe-8c84-11e6-876c-e4e17f9ac82c.png)

When I click explore/open the visualization, the graph is there:
![image](https://cloud.githubusercontent.com/assets/10057077/19185877/d7df6c02-8c83-11e6-9015-835cf64a85bb.png)

Can you help troubleshoot this?

**Comment by abyot** [comment]
@kreinhardt 

This usually happens when an invalid category / dimension is selected. I have removed the problematic graph. Can you tell me what were the different parameters you used to create the graph?

**Comment by kreinhardt** [comment]
**Data**: data element/[all]/details/Breastfeeding practices Pregnant and Lactating women 15-49 years
 **Periods**: 2014
**Organization unit**: National level
**Delivery Mechanism**: partial list selected (agriculture, assistance organizations, community, health system - facility, health system - community)
**Layout**:
![image](https://cloud.githubusercontent.com/assets/10057077/19187856/3bb25f8c-8c8e-11e6-9ceb-752a8e3ce0e9.png)

**Comment by kreinhardt** [comment]
hi @abyot, have you been able to look into this?

**Comment by abyot** [comment]
Yes, I have. I am in the process of upgrading to 2.25. It is coming soon.

**Comment by abyot** [comment]
now upgraded to 2.25, and the issue is fixed.
