### ISSUE TITLE
Translation file

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#36]
Hi @abyot  - is this still the translation file that we should use? https://raw.githubusercontent.com/abyot/sun-pmt/master/dhis-web/dhis-web-apps/src/main/webapp/dhis-web-action-mapping/i18n/i18n_app.properties

I think that we are finished changing any of the text in the mapping module so I want to start working on the translation with Chloe.

**Comment by abyot** [comment]
Yes, that is the file.

**Comment by kreinhardt** [comment]
Great, thanks @abyot . For translating to French, can I just send you a word document with the translations?

**Comment by kreinhardt** [comment]
hi @abyot, are there any restrictions with using accents when creating the translation file?

**Comment by abyot** [comment]
No... but we might need to do some encoding, we will see what happens once you have the strings.

**Comment by kreinhardt** [comment]
For the item: select_or_search_or_add=[Search from list or type \"new\"  to add]
-will the translation of "new" to "nouveau" still allow the user to type the word to add a new stakeholder?

For the item: ou_scope=Organisation unit scope 
-can you provide some context here so scope can be translated correctly? I'm not sure where this appears

**Comment by abyot** [comment]
hmm... we have a catch there :(

The following is automatically inserted in the system

{code: 'ADD_NEW_OPTION', id: 'ADD_NEW_OPTION', displayName: '[Add New Stakeholder]'};

This means, to be able to add a new stakeholder they need to type any one of the following - add, new, option, stakeholder - and the system will work. However, to avoid some confusion - would be nice if we can stick with words from displayName.

**Comment by kreinhardt** [comment]
@chloedenavit  just said that we should be able to use "new" in the French translation so we should actually be fine!

but @abyot  is the "displayName" in the code above linked to this (in the translation file): the add_new_option=[Add New Stakeholder] ?

**Comment by abyot** [comment]
no it is not linked. words in the translation file are just static texts that provide visual aide.

The ou_scope thing you asked me... I think we are not using it anymore. It was related to children, immediate children thing we introduced when generating reports. But now, we are using "Selected level", "Province", "District"...

**Comment by kreinhardt** [comment]
Can you upload the French translation file?
[SUN PMT translation file - French.docx](https://github.com/abyot/sun-pmt/files/657707/SUN.PMT.translation.file.-.French.docx)

**Comment by abyot** [comment]
Uploaded.

**Comment by abyot** [comment]
![image](https://cloud.githubusercontent.com/assets/4967749/21292594/84e06d60-c50b-11e6-9750-ff4bcdb612fd.png)

**Comment by kreinhardt** [comment]
Great! Thanks. We will have to have a french version of the metadata so that places where is has stakeholder roles and delivery mechanisms is translated.

**Comment by kreinhardt** [comment]
Hi Abyot - when looking at the system I noticed some errors in how the French was reading. Some of the code was appearing. 

![image](https://cloud.githubusercontent.com/assets/10057077/21931565/6ebc06d4-d99c-11e6-94d3-532c4467d444.png)


It seemed to be an issue with the file, where it looked like the code was on a new line but it wasnt. The amended file is here:
[SUN.PMT.translation.file.-.French.docx](https://github.com/abyot/sun-pmt/files/704374/SUN.PMT.translation.file.-.French.docx)

can you please re-upload this?

**Comment by kreinhardt** [comment]
Have you been able to update this? Out first country to use the system will be French-speaking.

**Comment by abyot** [comment]
This is applied.

**Comment by kreinhardt** [comment]
Chloe pointed out an issue with the french translation file. For the dropdown menu that lets you select the display level for SUN PMT reports. The translation of "district level" is wrong in french. This is an issue b/c in French the word order is different than in English. Is it possible to just remove "level" and it's translation from the system. That way the list will just include (1) selected level and (2) district (or whatever that org unit is called)?

![image](https://cloud.githubusercontent.com/assets/10057077/23166353/a4e75552-f840-11e6-9d05-10f422c3f18b.png)

**Comment by abyot** [comment]
sure, the word level is now removed.

**Comment by kreinhardt** [comment]
looks great. THanks @abyot
