### ISSUE TITLE
Action points from today's call

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#38]
Hi @abyot , just adding all the points we talked about since I wanted to make sure you have the exact text for the name change:
- [x] Change name of module to "SUN PMT"
- [x] No data appearing in the reports section of module
- [x] boxes with "x" appearing in additional stakeholder section when last stakeholder is removed
- [x] GIS module not loading
- [x] Metadata structure write up

Thank you!

**Comment by abyot** [comment]
Hi @kreinhardt , the issues we identified during the call are now fixed.

**Comment by kreinhardt** [comment]
Thanks @abyot. It looks the GIS module is working and the population report is working. 

I'm still have trouble getting the Who does what to show up:
![image](https://cloud.githubusercontent.com/assets/10057077/19556659/6358892e-96c2-11e6-8d93-608f5735ea16.png)

and the geographic coverage report:
![image](https://cloud.githubusercontent.com/assets/10057077/19556707/9fe6dd8c-96c2-11e6-87a5-0c1d239c66c5.png)


And I'm still getting the "x" appearing when removing stakeholders:
![image](https://cloud.githubusercontent.com/assets/10057077/19557035/41001d18-96c4-11e6-8627-4fc4afc6237c.png)

**Comment by kreinhardt** [comment]
@abyot  SORRY! Those things are fixed! I needed to clear my catch (I thought I had already done that...)
