### ISSUE TITLE
Adjustments to reporting tables

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#39]
- [x] Can you adjust the organization unit name above the table on all the reports so that the text is larger? To some size that is between what it is now and the size of the "Who Does What" report title in this image:
  ![image](https://cloud.githubusercontent.com/assets/10057077/19637699/af4b62f0-99d0-11e6-87d5-590c5c2a180b.png)
- [x] Can you also adjust this text to include more information so that when the table is downloaded the content of the table is clear? So the table title would be: _organization unit_ - _name of report_ (_role - if applicable_)
  Ex1: **Rwanda - Who Does What**
  Ex2: **East - Geographic coverage per stakeholder (funder)**
- [ ] When downloading the excel version of the reports - this happens: 
  ![image](https://cloud.githubusercontent.com/assets/10057077/19637934/b3cce2d0-99d1-11e6-9624-37f70e298b93.png)
  Can you advise on how to address this?
- [x] For the Population coverage per stakeholder report - can you fix the table so that it can scroll like the geographic coverage report?
- [x] Can you also remove the "0%" from the population coverage table - like with the geographic coverage report? So that when there is no data reported for an action/stakeholder, then the cell is blank.

**Comment by kreinhardt** [comment]
Another thing: not all the actions with no reported data are turning grey:
![image](https://cloud.githubusercontent.com/assets/10057077/19640823/cd261744-99de-11e6-88a7-835a2fa9dd2d.png)


If having the action where there is no data reported turn grey is difficult - it's ok to just leave the text black. However, I would want this to be consistent throughout the reports.

**Comment by abyot** [comment]
Hi @kreinhardt,

These are all fixed except the excel warning thing. I  do not have a solution for that... the thing is a typical problem of proprietary products. Microsoft Excel checks for strict formatting, literally rejecting anything that is generated with client side technology.

One solution that definitely works is that to tell each machine - that downloads and opens excel reports - not to check for strict formatting. However, this is not a good solution for many reasons.

**Comment by kreinhardt** [comment]
Thanks @abyot ! The tables are looking good. 

It seems like the actions not taking place are not being grey-ed out in the geographic coverage reports. Can you check this?

Can you also remove the option to download as a PDF? The tables look a bit weird b/c there are too wide for a normal page in this format. The excel feature is much more useful for us anyway!

**Comment by abyot** [comment]
Hi @kreinhardt 

Can you tell me the report parameters you have for geographic coverage?

**Comment by kreinhardt** [comment]
Sorry - I should have included that. 

Org unit: Rwanda
Reporting level: Province
Stakeholder role: Field Implementer (since all acitons have to have this filled....)
Actions: All

In the East Province, the action _Provide multiple micronutrient supplements (MNPs/Ongera)_ should be grey, as well as the _Schools_ target group for _Promotion of hygiene/handwashing_.

**Comment by kreinhardt** [comment]
It seems to be happening for some: 
![image](https://cloud.githubusercontent.com/assets/10057077/19678039/61e453d8-9a9c-11e6-91a9-2b69c4d80739.png)

![image](https://cloud.githubusercontent.com/assets/10057077/19678047/6ca7d060-9a9c-11e6-8818-f26efb65b19a.png)

**Comment by abyot** [comment]
Hi @kreinhardt,

Have made a fix just now. See if it working this time...

**Comment by kreinhardt** [comment]
Thanks @abyot  - looks good now!

One last change (I hope): can you change the text for the geographic coverage table to:

The table below presents the number and percentage of geographic areas that each stakeholder is supporting. The table can be created separately for each stakeholder role (field implementer, catalyst, funder and responsible ministry). The number and percentage in the table always refer to the sub-national level at which the data was collected. Use the 'Report filters' to define the geographic area, year, stakeholder role and actions to display.

![image](https://cloud.githubusercontent.com/assets/10057077/19679657/e1c00236-9aa2-11e6-8b4b-021d74beb88b.png)

**Comment by abyot** [comment]
Fixed.

**Comment by kreinhardt** [comment]
Thanks @abyot . One more.... (sorry, this really should be the last adjustment....)

Can you change the text for the population coverage table to:

The table below presents the percentage of beneficiaries covered by each stakeholder. The table can be created separately for each stakeholder role (field implementer, catalyst, funder and responsible ministry). Use the 'Report filters' to define the geographic area, year, stakeholder role and actions to display.

**Comment by abyot** [comment]
:(

Ok, I will add this one... but for the next ones, we will have to do it in batch ... like deploying fixes in every other day. 

It is a little inconvenient if I have to switch between my codebase and database every now and then

**Comment by kreinhardt** [comment]
I'm sorry!!!! This is the last one for now but in the future I will provide others as a batch. Thanks for doing all of these though! 

I'm going to look through everything again but I think that we are almost ready to clear and build the demo version if you have the description of the metadata structure ready for me?

**Comment by abyot** [comment]
Fixed. It is ok, it is just that I have to clear all the stuff from dashboard, replace with the mapping one. once done clear all the mapping stuff, replace with dashboard... and then repeat :(

**Comment by abyot** [comment]
I will try to have the metadata structure description document by Thursday. will that be late?

**Comment by kreinhardt** [comment]
Thanks @abyot  - Thursday for the metadata works for me. 

I will continue to  double/triple/... check things between now and then in case there is any other changes. However, I don't think there will much... if any.

**Comment by abyot** [comment]
ok, great.
