### ISSUE TITLE
Visualizations and maps

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#4]
A couple points I would like to review in our meeting today:
1. I cannot see data that I have input while in visualization, pivot tables or maps. Can we review this? There is probably a small step I'm missing. 
2. How to you upload data via .CSV (or other type of file)? I have a lot of situation indicator data in excel and it would be faster/more accurate to be able to upload than to input by hand.

**Comment by kreinhardt** [comment]
Send situation indicator data to Abyot.

**Comment by kreinhardt** [comment]
I've updated the .CSV with the proper names - this issue was that for the districts the names did not include "district" at the end. I fixed this and not have the proper IDs for each org unit. The new files is named "Situation indicators-with orgunit id v2" in the google drive folder.

**Comment by abyot** [comment]
For updating data we use Import/Export module. It allows for importing/exporting both data and metadata.

Analytics needs to be run to see data in any of the output modules.
