### ISSUE TITLE
Issue with adding stakeholders

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#40]
Hi @abyot  - can you look into this? It's taking a long time (in fact, has not finished) to add a stakeholder.

![image](https://cloud.githubusercontent.com/assets/10057077/19811603/69355aea-9d32-11e6-8f32-32ee0e881992.png)

**Comment by abyot** [comment]
Hi @kreinhardt 

Looking at the screenshot, the red thing to the right is the interesting part. Seems there is a conflict. Either World Bank or WB exist in the system. Can you check that?

**Comment by kreinhardt** [comment]
I do see it under the category option set - but the one I tried to create a couple hours ago. 

Let me try a new stakeholder and report back.

**Comment by abyot** [comment]
For stakeholder, we are adding in two places
- as category option (assigned to category Stakeholders)  and
- as option (assigned to Option set Stakeholders)

Option sets are available under Apps -> Maintenance -> Other

**Comment by kreinhardt** [comment]
Ok, I will check option as well. 

But I just tried to add a new stakeholder and have been waiting for it to clear for the last 10 min:
![image](https://cloud.githubusercontent.com/assets/10057077/19812296/3f640b3c-9d35-11e6-9543-947df4d0ae1a.png)

**Comment by kreinhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/10057077/19812823/729d842c-9d37-11e6-898f-2cb95cf37fb3.png)

**Comment by abyot** [comment]
Hi @kreinhardt 

This is fixed. Please test it from your side. Make sure to clear your cached before testing.

**Comment by kreinhardt** [comment]
This looks good from my side. Thanks @abyot
