### ISSUE TITLE
Another issue with district specific additional stakeholders

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#41]
Hi @abyot - can you look into the district specific stakeholders for cases where there is more than one target group? It seems like when a stakeholder at the district level is added - that stakeholder is being added for both target groups, even if it is meant for only one. 

![image](https://cloud.githubusercontent.com/assets/10057077/19938661/0b3919b6-a126-11e6-83e7-b6fdd125538b.png)

**Comment by kreinhardt** [comment]
Hi @abyot  - have you been able to look into this? It is the last issue to be fixed before clearing and building the clean demo version. Thanks.

**Comment by abyot** [comment]
Hi @kreinhardt 

This should be fixed. Please test it and let me know if still remains an issue.

**Comment by kreinhardt** [comment]
Great! It looks like it's fixed!
