### ISSUE TITLE
List of stakeholders not coming up

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#45]
Hi @abyot , in the SUN PMT data entry the stakeholders for the catalyst, funder and responsible ministry are not coming up! I thought I had made all the links but I guess not. Can you take a look and let me know where I'm going wrong?

![image](https://cloud.githubusercontent.com/assets/10057077/20625900/52bc3ac8-b316-11e6-9da6-5611e3662412.png)

**Comment by abyot** [comment]
It was two things... sorry that I did the fix myself, that was the only way for me to find out the problem :(

1. The option sets Stakeholders and Reponsible Ministry need to have a new attribute called 
name= "Stakeholder Role"
code = "StakeholderRole" assigned to them. This attribute should be of type Text and linked to another option set again called "Stakeholder Role" - I chose the same name for simplicity. This option set will then have two options 
[{name: Funder, code: Funder}, {name:Responsible Ministry, code: ResponsibleMinistry}]. 

Then the two option sets - Stakholder, Responsible Ministry - need to have their type configured. Stakeholder will be of type Funder and Responsible Ministry type Responsible Ministry.

2. the second issue was there was a missing code for data element Responsible Ministry.

**Comment by kreinhardt** [comment]
Thanks Abyot - it okay that you fixed them. a couple questions:
1. In the option sets, what is the difference between the "Stakeholder role" and "Roles""? The new "Stakeholder" role does not have "Catalyst" as an option but other wise looks the same?

2. In attribute there are now two "stakeholder roles" one is assigned to data element and one to option set. Are both of these needed?
