### ISSUE TITLE
"additional stakeholders" not showing up for some actions

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#47]
I found 3 actions where the additional stakeholders were not showing up properly. I went back and looked at each part of the metadata but they seemed to be in order. 

![image](https://cloud.githubusercontent.com/assets/10057077/20651025/41bba1f0-b4dd-11e6-8c01-42f2f789d9b0.png)

![image](https://cloud.githubusercontent.com/assets/10057077/20651089/83a9dcfc-b4de-11e6-8a89-b9c5a1ee8386.png)

![image](https://cloud.githubusercontent.com/assets/10057077/20651104/cb4b226e-b4de-11e6-8639-a2214f1fb4c7.png)

**Comment by abyot** [comment]
Hi @kreinhardt 

A most probable cause here is that something is not properly defined for corresponding programs. Here is what to check:

1. does the program exist? Program and action are linked through action code
2. does the program have program stage and the program stage data elements?

**Comment by kreinhardt** [comment]
So I checked the 3 actions - they all have programs and are associated with the correct action code. 

2 of them did not have program stage data elements so I have now fixed that. The action iron/folic acid supplementation already had program stages so I'm not sure what is happening with that one...

**Comment by abyot** [comment]
Daily iron and folic acid supplementation, code for program is Ac9 while code for data element / action is AC9 - note the c Vs C. This means you need to change to code in option set... however it is not possible to edit code. what you can do there is remove the option (not the option set) and recreate with the proper code

Deworming works... may be a cache issue?

**Comment by kreinhardt** [comment]
Deworming wasn't an issue after I added the program data elements. 

I fixed the option and reassigned the code to the program so the iron actions is showing up now.
