### ISSUE TITLE
User role definitions

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#50]
Hi @abyot - can you send me the user role definitions for the 3 roles your described (superuser, data entry and viewing, and just data viewing)?

**Comment by kreinhardt** [comment]
just following up on this

**Comment by abyot** [comment]
Here are the three roles:

1. Superuser is superuser :)

2. Data viewing 
- See Data Visualizer module
- See GIS module
- See Pivot Table module
- See Report module
- See Dashboard integration module

3. Data entry and viewing
_- All data viewing roles_

- Add/Update Data Value
- Delete Data Value
- See Dashboard integration module
- See Data Entry module
- See SUN PMT module

- Add/Update Tracked Entity Data Value
- Delete Tracked Entity Data Value

- Add/Update Private Data Element Category Option
- Add/Update Public Data Element Category Option
- Add/Update Private Data Element Category
- Add/Update Public Data Element Category
- Add/Update Private Data Element Category Combo
- Add/Update Public Data Element Category Combo
- Add/Update Private Option Set
- Add/Update Public Option Set

- Access to all data sets and programs.

A modular approach to implement this is to create the three (actually two excluding the superuser) roles. Then for data entry and view users assign them both data view and data entry roles.

**Comment by kreinhardt** [comment]
Thanks for this. When creating the roles do I need to set the data sets and programs?

**Comment by kreinhardt** [comment]
And, for the last point about the modular approach - do you mean that I can create the data entry role without the data viewing aspects - then assign the two roles to the users with viewing and entry privileges?

**Comment by abyot** [comment]
Yes, when creating the roles you need to assign data sets and programs.

Re: the modular approach: Yes, that way you can reuse the roles for other groups of users. 
- Data view can have only data view role
- Data view and entry can have data view and data entry roles.

**Comment by abyot** [comment]
oh sorry, I thought I have fixed that.

User "M_dhis-web-action-mapping" for now. I will update the server later.

**Comment by kreinhardt** [comment]
Ok! thanks

**Comment by abyot** [comment]
alternatively you can also use the share button on the dashboard

![image](https://cloud.githubusercontent.com/assets/4967749/21685291/556a596a-d361-11e6-9ef2-2ed8c0c61dcb.png)

Unlike the sharing of the entire selected dashboard for anyone from a given orgunit (the one you can do through the gear icon), the share button allows you to share based on user group.

**Comment by kreinhardt** [comment]
Great - thanks. 

From the share button - I also just selected public view with login / can edit. It seemed to work for my demo user I created. But are there any issues or limitations that I should be aware of with this method?
