### ISSUE TITLE
legends/maps

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#53]
Hi Abyot, I need to make my maps so for districts where this is no data the district is either a different color or blank. I tried making a new legend to do this but have not had success. 

For example, this is what my map looks like where there has been no data enter for this action. 
![image](https://cloud.githubusercontent.com/assets/10057077/22099592/44bcb272-de2c-11e6-9cb4-c74efb8ab508.png)

**Comment by abyot** [comment]
Not sure I understand the issue here. Can you provide me more info?

**Comment by kreinhardt** [comment]
The issue for me is that I'm not sure how the legend works. I'm trying to set it so that when there is not data enter (and the system has stored this as 0) - the map will show up as a particular color. Then for above 0, I have my five divisions. 

This is what I have tried to set but it's not working: 
![image](https://cloud.githubusercontent.com/assets/10057077/22208709/1a834e7a-e184-11e6-9f03-7644f3da8acd.png)

**Comment by abyot** [comment]
Hmm... not sure if that is possible. but will ask the people here.

Legend 0 - 25 has already taken care of 0 - 0.

Can you try 1 - 25 instead?

**Comment by kreinhardt** [comment]
The legend distinction needs to be between 0 and 0.001 (i.e. anything number above 0). This is only for visualization purposes so if this is not possible to do via the legends, then it's ok and we can make do with how we currently use the gis app.

**Comment by kreinhardt** [comment]
Hi @abyot - were you able to follow up on this?

**Comment by abyot** [comment]
Yes, and that is not possible :(

**Comment by kreinhardt** [comment]
ok - no problem. thank you.
