### ISSUE TITLE
adding items to dashboard

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#55]
Hi @abyot - can you tell me how to increase the size of my dashboard
![image](https://cloud.githubusercontent.com/assets/10057077/22102524/06f6767e-de38-11e6-952e-d3898e8967de.png)

I looked up can't find it in the settings...

**Comment by kreinhardt** [comment]
also note that the items actually appear after I refresh....

**Comment by abyot** [comment]
Emm... I think it will be an issue later.  

Probably better to break the dashboard into more pieces --- scrolling down through such items is not a healthy thing. Keeping few items would have a feeling of dashboard - where everything is accessible without browsing through :)

**Comment by kreinhardt** [comment]
I agree - it just it might be hard to avoid this.... For now I have split it and hopefully countries will be able to do that same.
