### ISSUE TITLE
data not being recorded

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#56]
Hi @abyot - I was using the system today and noticed that the additional stakeholders are not being recorded.
This is what I find when I got back to an entry where I had additional stakeholders entered:
![image](https://cloud.githubusercontent.com/assets/10057077/22151199/52fe6a96-df1d-11e6-82ae-ff27cc7f4898.png)

**Comment by abyot** [comment]
not able to reproduce this... may be related to some kind of timeout like the browser staying idle for sometime and you trying to enter data ....

Can you try one more time after refreshing your browse ... or may be to be sure clearing your cache?

**Comment by kreinhardt** [comment]
So, I was able to save data properly from home... not sure why this was happening at work. 

Have you come across this issue with other projects? Is it something in my settings? Or my internet while at work?

**Comment by kreinhardt** [comment]
this has not happened again. I think it was my internet connection that day.
