### ISSUE TITLE
report with all data entered

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#57]
Is it possible to put together a quick report that can be used to check the data that has been entered?

It would be nice if this could look like the database found in the tool - where there is a line of data for each action + target group + org unit with all the data on corresponding beneficiaries, field implementer and additional data. It also wouldn't hurt if you can add the user and date who entered the data (but only if it's easy....)

Let me know if you need more information from me - again, really just looking for something that the admin would look at in case there are any data issues.

**Comment by kreinhardt** [comment]
just checking to see if you have come up with anything here. Thanks!

**Comment by abyot** [comment]
sorry, unfortunately I couldn't find a quick solution.

**Comment by kreinhardt** [comment]
no problem. Thanks for checking.
