### ISSUE TITLE
adding years

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#58]
Hi - quick question. Is it possible to add more years to the system? In the normal data entry section, I can only enter data from 2012 or later. I'm just adding a couple finishing touches and would like to show some background data over a couple years.

I would be nice to have 10 years (so starting at 2007 - 2016) as options. 

Thanks

**Comment by abyot** [comment]
sorry we have no setting for that ... but you can always use the arrows / buttons next to the period / year.

**Comment by kreinhardt** [comment]
ohh ok - it's showing up now. I had to use the arrow button and then go back to the dropdown.
