### ISSUE TITLE
Adding French metadata

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#59]
Hi Abyot - I'm having trouble adding the french metadata. I have gotten these errors:

When trying to add the data set for the action:
![image](https://cloud.githubusercontent.com/assets/10057077/22254247/4e299420-e254-11e6-98c5-c40a8f57575c.png)

When trying to add the new target group to the target group data set:
![image](https://cloud.githubusercontent.com/assets/10057077/22254368/ae0294a0-e254-11e6-9c0f-d7e1aca79b2f.png)

**Comment by abyot** [comment]
you don't have to add a new metadata... rather translate an existing metadata into a different locale / language.

Right click on any metadata (most are supported except few) -> click on Translate -> select locale -> ...

**Comment by kreinhardt** [comment]
ok! Got it. 

I have translated an action, target group, and a couple of the stakeholders but it looks like it's mostly working:
![image](https://cloud.githubusercontent.com/assets/10057077/22258221/0631dec2-e261-11e6-89fd-ed6c703154f2.png)

There are two things that seem to be an issue. 
1. I can't get the target group to change! I had translated "households" to "Ménages"
2. The abbreviations for stakeholders cannot be translated when an option set because they are used as the code that is also used to search for stakeholders.

In general, I don't think this will be an issue because for each country where the system is deployed - the admin will be setting up the metadata and can set it up in their own language.

**Comment by abyot** [comment]
Ok, the thing with "households" should work, if not there is something which I missed and will be fixed.

As to the code, it is not possible to translate codes. The reason is that they are used internally by the system ... as the name implies they are just CODEs which are not meant to human :(

**Comment by kreinhardt** [comment]
So I translated "households" under category option and data element. But I still cannot get the translation to show up. 

I did find this under category option combination... and I cannot translate these. 

![image](https://cloud.githubusercontent.com/assets/10057077/22284679/a56fdb60-e2e8-11e6-9d51-bed3d4829ba7.png)

**Comment by abyot** [comment]
Category option combination is not translatable. It is generated based on the combinations of options assigned to categories. Again the reason for this is that it is more of an internal thing, of course we are using it to store value. Its name comes by combining names of category options. The moment a category combination is created, the system will generate category option combination ... had it been a case where the category / options were created in the language of your choice,  - the option combinations would have generated in the corresponding language... as mentioned will fix this as we shouldn't directly use the category option combination names rather the translated versions of categories and options... that way we will have things showing up in the selected language locale.... I will take a look to this.

**Comment by kreinhardt** [comment]
Here are some additional areas where translation is not taking place:

The top portion of the table and the contents of the table (target groups, delivery mechanisms, stakeholder names) is not translating:
![image](https://cloud.githubusercontent.com/assets/10057077/22287710/1a0b3428-e2f4-11e6-8903-c57086ea31e6.png)

The dropdown list of stakeholder roles is not translating: 
![image](https://cloud.githubusercontent.com/assets/10057077/22287724/3000b7b2-e2f4-11e6-88b7-8c9ebcd70f0a.png)

In the tables for the population and geogrpahic coverage, the one of the responsible ministries duplicated it's self in the translation part, but otherwise did not translate:
![image](https://cloud.githubusercontent.com/assets/10057077/22288186/09760a0a-e2f6-11e6-9995-410b1a18edd6.png)

**Comment by abyot** [comment]
The missing translation part is not an issue... will be fixed soon. The thing I am unsure is the duplication thing you mentioned. Was it only the Ministry of Health which got duplicated? Or all of them? do you remember anything particular with it?

**Comment by kreinhardt** [comment]
Yes - it's the ministry of health that was duplicated - "Ministère de la Santé". It's happening on the english version now too! I'm not sure what I did to make this happen...  for everything I translated,  I used the _translate>locale>..._ process you mentioned above. I looked for "Ministère de la Santé" in the stakeholder and responsible ministry option sets and the category options and did not find it. 

English version of report:
![image](https://cloud.githubusercontent.com/assets/10057077/22290298/44dcbd1e-e300-11e6-9522-f17701c67846.png)

**Comment by kreinhardt** [comment]
Hi @abyot  - I'm having a bit of trouble with the translation aspect. Not all of my translations are coming through (highlighted in yellow below). Can you take a look?

![image](https://cloud.githubusercontent.com/assets/10057077/22597530/4574f840-ea30-11e6-90dd-c423c012a56a.png)

![image](https://cloud.githubusercontent.com/assets/10057077/22597599/91620ac2-ea30-11e6-9977-e4b456b8e833.png)

**Comment by kreinhardt** [comment]
just checking on this and it looks like something has gotten mixed up:
![image](https://cloud.githubusercontent.com/assets/10057077/22741267/faa505d4-ee40-11e6-94dd-094c755f6899.png)

Can you check this out?

**Comment by kreinhardt** [comment]
ok - so looks like the only things that needs to be translated is the target group:
![image](https://cloud.githubusercontent.com/assets/10057077/22823503/5f404964-efb2-11e6-83ee-1581d5202c79.png)

I have translated this in the metadata (data element and category option) but it does not seem to be coming through.

**Comment by abyot** [comment]
Yes, there are some issues with that. Actually I have already made a fix for example to the stakeholder names to render in selected language. Will do the same for the target groups as well - just that didn't have the time. I will update the server over the weekend.

**Comment by kreinhardt** [comment]
Great - thanks @abyot

**Comment by kreinhardt** [comment]
Hi @abyot - have you updated the system? I looked (after clearing my cache) but still see the target groups in english.

**Comment by abyot** [comment]
Hi @kreinhardt , sorry for the delay.

The server is now updated ...

![image](https://cloud.githubusercontent.com/assets/4967749/22973073/ce7e43ee-f37c-11e6-8b9e-ded2a7374e2a.png)
