### ISSUE TITLE
Action points from today's call

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#6]
- [x] Create the option for user to input "N/A" for donors, responsible ministry and catalyst
- [x] Change the data entry to be per action and allow for entry of data for multiple districts
- [x] Add secondary and tertiary options for donors and catalysts
- [x] Add descriptions for each of the donor roles (will be included in mock-up...)
- [x] Create mock-up for data entry (Kris will send this early next week)

**Comment by abyot** [comment]
Now data entry is configured to be per action and allowing entry for multiple districts. See sample screenshots below

![image](https://cloud.githubusercontent.com/assets/4967749/16356017/56322182-3aca-11e6-80f6-e54fac84a522.png)


![image](https://cloud.githubusercontent.com/assets/4967749/16356013/26aaeafc-3aca-11e6-857f-df4766a8b4bf.png)
