### ISSUE TITLE
Pop-up boxes in data entry

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#60]
Hi @abyot  - I'm really sorry but the pop up boxes for the "additional stakeholders" are not working.

Just the ones circled (the others are working):
![image](https://cloud.githubusercontent.com/assets/10057077/22978707/1326e7d2-f394-11e6-827b-92992164e4df.png)

**Comment by abyot** [comment]
The popups show if you description for the data elements. See if data elements Catalyst, Funder and Responsible Ministry have descriptions?

**Comment by kreinhardt** [comment]
ooooooohhhhhhhh.... got it. Sorry. I will sort this out. For some reason I thought that it was part of the translation file.

**Comment by abyot** [comment]
no, it comes from the description. you can also translate it from the data element menu.

**Comment by kreinhardt** [comment]
ok! perfect. thank you.
