### ISSUE TITLE
Translating the name of the system

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#62]
Is there a way to translate the title of the system? I have already translated this title under system settings > appearance. The change shows up on the login page but not the home page. 

![image](https://cloud.githubusercontent.com/assets/10057077/23025615/d187e300-f45e-11e6-994b-a8f47e5da1ca.png)

![image](https://cloud.githubusercontent.com/assets/10057077/23025586/b94e0e4a-f45e-11e6-8875-453eec7b01b8.png)

**Comment by abyot** [comment]
No, sorry. Unfortunately we have a bad design over there... the two are supposed to be the same but they are not. Fixing that is not easy as we have to redesign that specific feature.

We would be happy if you could create a JIRA issue here https://jira.dhis2.org

We will implement it in the standard DHIS 2 as well.

**Comment by kreinhardt** [comment]
Ok - I'm happy to raise the issue on JIRA. I just created an account. No do I create an issue under DHIS2 software + improvement?

**Comment by abyot** [comment]
Yes, improvement :)
