### ISSUE TITLE
Cannot add new stakeholders

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#65]
Hi Abyot - I have been testing out the SUN PMT now base don the WFP servers and found that I cannot add new stakeholders:

![image](https://cloud.githubusercontent.com/assets/10057077/25137279/9a0eac50-2457-11e7-8b3c-97c29c129c1f.png)

I'm not sure what 409 conflict means in this context but I double checked and the new stakeholder I was adding was not already in the system.

I also tried this on the SUN PMT still on your server and get the same thing:

![image](https://cloud.githubusercontent.com/assets/10057077/25137268/9147b864-2457-11e7-8802-4d3c3d985e85.png)

**Comment by kreinhardt** [comment]
Hi Abyot - I was wondering if you have had time to look at this. We have a call next week where we are going to demo the tool with a country who is interested and it would be great is this feature could be back up. Thank you!

**Comment by abyot** [comment]
Hi Kris,

Since this happened on your server, I don't have access to the log file and difficult to know what the issue is. However, given the 409 error, I suspect there is a conflict - are you sure you are not duplicating name / code? Have you tried again?

**Comment by kreinhardt** [comment]
Yes - I have tried several times to add stakeholders. Each time picking different names (and also double checking that they are not already part of the metadata)

Here is the screenshot from the WFP server:
![image](https://cloud.githubusercontent.com/assets/10057077/25799700/58e0907e-33e6-11e7-899e-f455657b4ee5.png)


**note** that the same thing is happening on your server too (since I have not made changes to the WFP version of the tool, these should still be the same).
Here is a screen shot from the same thing happening on your server:
![image](https://cloud.githubusercontent.com/assets/10057077/25799765/a39a6a5e-33e6-11e7-85b1-f1240b090507.png)

**Comment by kreinhardt** [comment]
Hi Abyot- just checking in. This is still happening and on the SUN PMT that is on your server:
![image](https://cloud.githubusercontent.com/assets/10057077/26107402/741ea8c6-3a49-11e7-9184-924fddbd1b8d.png)

![image](https://cloud.githubusercontent.com/assets/10057077/26107417/809c8596-3a49-11e7-9a4b-850f23fb6b85.png)

Can you figure out the issue on your server and then we can push the fix to the wfp server.

**Comment by abyot** [comment]
Hi @kreinhardt 

I just updated the test server. Please do some tests and once you confirmed we can tell the IT team to deploy the new war file.

**Comment by kreinhardt** [comment]
Thanks @abyot . 

I was able to add a new stakeholder. But I couldn't add a second one for the same value (i.e. I added one under field implementer but coouldnt add a second one - I had to enter a new one under the other partner names). I can't remember of this is how it worked before. Do you know?

**Comment by abyot** [comment]
Sorry, I didn't get you.

The rule is that both name and abbreviation has to be unique... so not possible to use the same value.

**Comment by kreinhardt** [comment]
Sorry - I did a poor job explaining. 

So, I added a new stakeholder ("Engineers without Borders") through the field implementer field. After it added, the form reset. I then tried to add a new stakeholder again through the field implementer field but when I searched "new", I wasn't given the option to add a new stakeholder. This is what happens:

![image](https://cloud.githubusercontent.com/assets/10057077/26441994/005530ea-4133-11e7-9962-eeaea48447ca.png)

I was able to add a new stakeholder through the catalyst/funder fields:

![image](https://cloud.githubusercontent.com/assets/10057077/26442023/197c29c0-4133-11e7-8e98-f40137bfe6ae.png)

To enter a second new stakeholder under field implementer I had to clear the cache...

**Comment by abyot** [comment]
Oh I see... have you tried it after refreshing also?

**Comment by kreinhardt** [comment]
I had tried going to the dashboard and then going back to the SUN PMT module - is that the same thing?

**Comment by abyot** [comment]
hmm... ok will look into it.

**Comment by abyot** [comment]
It should be fine now. Please try it one more time.

**Comment by kreinhardt** [comment]
Great - it looks like it's working. I was able to add several without a problem. 

Do I need to initiate the update? Or can you just email them and cc me?

**Comment by abyot** [comment]
I think so, let them know that the latest war file can be found from here 

https://drive.google.com/open?id=0B0fAx5QYcDhmZEtiWGp3SlNCNHM

**Comment by kreinhardt** [comment]
great - will do. 

Thanks Abyot.
