### ISSUE TITLE
special reports for field implementer not showing up

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#66]
Hi @abyot - WFP has uploaded the new version to the WFP server and the add new stakeholder feature is working. 

The special reports (population coverage per stakeholder and geographical coverage per stakeholder) is not working for the field implementer. However, this is working on your server... can you advise on what to do? Should I have WFP migrate again?

In case you want to look at the website the URL is: http://mappingdemo.unnetworkforsun.org (the login should be the same but if not and I can send via email)

**Comment by abyot** [comment]
What are the report params / filters so that I can test ?

**Comment by kreinhardt** [comment]
Sorry! I forogt to write to you here! 

I tested again this morning and they worked. 

If you want to double check, the params are for both geo coverage and pop coverage reports:
-any organization unit
-year: 2015
-any level (selected or disaggregated)
-Field Implementer
-any/all actions

**Comment by kreinhardt** [comment]
I think that we are okay on this - so I'm closing the issue.
