### ISSUE TITLE
files for deployment

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#67]
Hi @abyot 

I thought of one last thing I need from you regarding the SUN PMT. Can you send me a link to a version of the tool with a blank database and without defined metadata. This will be the file that we send to countries who want to deploy the system if they DHIS2 expertise available.

**Comment by abyot** [comment]
The war file - the link I sent you earlier - is the only thing they need. Given the war file, one just has to follow standard DHIS2 installation.

**Comment by kreinhardt** [comment]
Since I'm not familiar with the standard DHIS2 installlation process, this person could take the file and clear the database and metadata easily?

**Comment by kreinhardt** [comment]
Hi @abyot - We are being asked to send the file to a country for deployment and I need to confirm that there will be no data from the demo in the WAR file I send to the country.

**Comment by abyot** [comment]
Yes, that is correct.
