### ISSUE TITLE
Clearing the database

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#68]
Hi @abyot - is it possible for you to clear the database on the SUN PMT that is on your server? It would be helpful for Chloe and I to have a clean database when we have a training session next Tuesday on how to build the metadata. 

Thank you.

**Comment by abyot** [comment]
Hi @kreinhardt - clear the database means only data or both data and metadata?

**Comment by abyot** [comment]
ok, it is now on blank database.
