### ISSUE TITLE
Unique category combination for action

### ISSUE THREAD

**Issue by abyot** [abyot/sun-pmt#7]
Which one are we taking as unique combination: 

1. "Delivery mechanism"  
2. "Delivery mechanism" and "Field Implementer" ?

**Comment by kreinhardt** [comment]
Delivery mechanism and field implementer

->We expect that the same action + target group + delivery mechanism are taking place in the same geographic locations but through different field implementers. We want to capture these a different data points and be able to aggregate the coverage for a particular action + target group + delivery mechanisms + geogrpahic location combination across all the field implementers who have been reported.
