### ISSUE TITLE
Adding population data (denominators) into the Data Entry module

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-pmt#70]
Hi @abyot ,
I tried to enter some population data through the Data Entry App but the screen didn’t enable me to enter the numbers. It also said “no org unit” selected and “no data element selected”. Could you help?

Here's a screenshot: 
![image](https://user-images.githubusercontent.com/21313941/27832419-f4a6554c-60ce-11e7-92cf-e23f0f1a4102.png)

**Comment by abyot** [comment]
Hi @chloedenavit  seems we have an issue there ... see a log below. This happened since June 15 - I need some time to fix this.

![image](https://user-images.githubusercontent.com/4967749/27859781-2ddb058c-617a-11e7-9703-c2127b12fc04.png)

**Comment by chloedenavit** [comment]
OK, thanks. Could you give me an estimate of timing? 

We have the HISP West Africa colleague hopefully coming to be trained on the SUN PMT the week of July 23rd, for your info.

**Comment by abyot** [comment]
I need something like 2 or 3 full days. Seems all the three systems need to be fixed. Will try to make it this weekend and before leaving to Addis (I am leaving on the 12th).

**Comment by chloedenavit** [comment]
OK, thank you very much. 

If I need to ask WFP to update the demo version we have on their server, don't forget to send me the files for me to send to them. Thanks!

**Comment by abyot** [comment]
Hi @chloedenavit ,

One thing I just noticed ... I don't think target group data elements have category dimension. Can you clarify this with Kris?

Data entry fails because of this ... of course we also have the security warning which I need to fix.

**Comment by chloedenavit** [comment]
Yes, you're right, that was my mistake! I'm sorry. I removed the category dimensions and now it's working. Kris' guidance was correct but I misread it. :)
