### ISSUE TITLE
Change on the data entry view entry levels 

### ISSUE THREAD

**Issue by margaret822** [abyot/sun-pmt#79]
User accounts to be set to access only district lever and not province. Tool to be modified to have data entry to be done at District Level, not provincial level

**Comment by abyot** [comment]
The system now supports data entry at multiple levels. The system detects selected level and renders the entry form accordingly.

This can be tested in the demo systems:

http://109.237.25.74:9090/sunpmt

http://109.237.25.74:8282/zmpmt
