### ISSUE TITLE
Reports and Stakeholders

### ISSUE THREAD

**Issue by abyot** [abyot/sun-pmt#8]
We have the following reports based on stakeholders
Who does what
Geography coverage per stakeholder
Population coverage per stakeholder

Are we expecting any other analysis, report, output based on stakeholders? 

Also, can we stick to the current format/layout of reports on stakeholders?

**Comment by kreinhardt** [comment]
Yes, we want the following report/analysis:

Who does what (at the national, provincial and district levels)

Geographic coverage of each action+target group at national (number of provinces out of total) and provincial (number of districts out of total for a particular province) levels: 
-per stakeholder (coverage for each stakeholders separated by role)
-per delivery mechanism (aggregated across stakeholders)
-overall (aggregated across all delivery mechanisms and stakeholders)

Population coverage of each action+target group at district level and aggregated to provincial and national levels: 
-per stakeholder (coverage for each stakeholders separated by role)
-per delivery mechanism (aggregated across stakeholders)
-overall (aggregated across all delivery mechanisms and stakeholders)

Not clear which layout you are asking about - the table in the tool where there is an action on each row and stakeholders in each column? Yes, this layout is good.
