### ISSUE TITLE
Actions point for data entry from 03/08 call

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#9]
**(1) Separation of Action and Target Group**: The action and target group will be separated so that the user will first select the action via the dropdown menu and then select the target group via the next dropdown menu. The target group list will be dependent on the action selected. 
- [x] Abyot will make this change

**(2) Adding a new stakeholders**: 
- Adding new stakeholders is taking a long time (10+ minutes). 
- [x] Abyot will look at the log from Tuesday/Wednesday to identify/fix issue (in the future Kris will send the log for issues of this nature)
- We would like to adjust the pop-up box for adding a new stakeholder to make it simpler for the user by adding a line of directions and removing the requirement for the user to enter a code. 
- [x] Kris will send text for directions to be added to the pop-up box
- [x] Abyot will use the abbreviation as the code so that users do not have to enter a code.

**(3) Note on right-side for when data has already been entered**: 
- The note is appearing even when there is no data entered for the stakeholders (catalyst, funder, responsible ministry) and number of beneficiaries (this includes instances when there is no previously entered data / audit trail).
- [x] Abyot will work on fixing this
- We would like to modify the text to be clearer about what data is already entered and what the user should do to proceed. 
- [x] Kris will send text to be used

**(4) Blank cells appear green**: Cells without data are appearing green prior to data entry (see attached image). This seems to be happening when one of the unique identifier components is changed and the green is residual from a previous data entry screen.  
- [x] Abyot will fix this

**(5) District-specific partner icon and instructions**: We would like to add some additional instructions for users and change the icon for the district-specific partner identification.
- [x] Kris will send a mock-up for text to be added under the partner columns (one sentence across all three)
- [x] Abyot will share a file of DHIS2 icons (the icons can also be changes for the Action Mapping Reports)

**(6) “Complete”/”Incomplete”/”Run Validation” buttons at bottom of data entry form**: Abyot wants to know if we have a use for these buttons. If someone clicks “Complete”, they are certifying that all of their data has been submitted and they are not expecting to do any additional data entry. We can also generate a report of which data entry screens have been started but are not marked complete so that we can follow-up as necessary.  
- [x] We will keep these buttons with no restrictions about who can click "Complete" or "Incomplete". This way users can go in and modify past data if they need to, and we can generate a report about which sheets are complete or not.

**(7) Generating completion reports**: We would like a report of which stakeholders have submitted data. Reports can be run even without the “Complete” button being clicked.

**(8) Access for users entering data**: We want to define a stakeholder as only having Data Entry access. Once data is complete and validated, we can give them access to reports that have been verified. We assume that different users will have different user rights.

**(9) Data validation during data entry**: Simple data validation is needed so that values entered are not greater than the denominator. This can created through Apps -> Data Quality -> Validation Rule -> Add New where the right and left sides of the condition can be defined.

**(10) Comments for values**: We would like to add a comment box to the History and Audit Information pop-up box, similar to the pop-up in the original data entry module. 
- [x] Abyot, can you do this?

**Comment by abyot** [comment]
Yes, I can implement the feature to record comments for values (task #10).

Icons to choose from: http://fontawesome.io/icons/

Sample translation file to start with: https://raw.githubusercontent.com/abyot/sun-pmt/master/dhis-web/dhis-web-apps/src/main/webapp/dhis-web-action-mapping/i18n/i18n_app.properties

About the translation - may be we can discuss this in our next call. How about the other modules (I mean the standard DHIS2 modules)? Have you checked if we have all the modules fully translated to the language of our choice?

**Comment by kreinhardt** [comment]
Here is some of the text additions that we discussed: 

**Text for pop-up when adding a new stakeholder:** 
"If the stakeholder is not on the current list, please add the stakeholder’s name and abbreviation here. It will automatically be added to all stakeholder lists." (See mock up for formatting)

**Note for right-side:** 
"**Warning**: On <date>, user <username> last entered data for the same action, target group, field implementer, delivery mechanism and geographic location.
If the Additional Stakeholders or the numbers of beneficiaries that were previously entered are not correct, please revise the information or contact the system administrator."

**Directions for changing stakeholders at district level:**
"If stakeholders differ across the geographic areas below, use the <icon> icon to modify the stakeholders supporting each area." (See mock up for formatting)

**Pop-up for changing stakeholders at district level:**
"If the Additional Stakeholders differ in this geographic area, please make the necessary modifications here." (See mock up for formatting)

- [ ] **Can you add a title to the section where you add the addition stakeholders called "Additional Stakeholder"?** (See mock up for visualization of what I mean)

New mock up with text here: [https://drive.google.com/open?id=0B9AJjRbFGuGtVmhTd0lyeTRFMWM]
